#Here i am using st.secrets to access the environment variables securely in my Streamlit application. This way, I can keep my sensitive information like API keys and email credentials safe while still being able to use them in my code during streamlit app deployment.

GEMINI_API_KEY="AIzaSyCdutQmf13ixOorr2sUcIqReB4cKyFXa_0"
EMAIL_ADDRESS="khushgodani123@gmail.com"
EMAIL_PASSWORD="orsy rdvx tpht mdtk"